---
- name:  Crea o Borra un valor de la Registry. 
  hosts: WINDOWS2012R2
  gather_facts: false

  roles:

     #- borra_clave
     - role: crea_clave
       when: accion == 'crear'

     - role: borra_clave
       when: accion == 'borrar'

