---
- name: Instala un httpd.
  yum:
     name: httpd 
     state: present

- name: Se asegura que este levantado. 
  service: 
     name: httpd 
     state: started

  - name: Restartea el httpd.
    service: 
      name: httpd 
      state: restarted
