---
     - name: Login to oVirt
       ovirt_auth:
         url: https://rhevm4.herdom.com/ovirt-engine/api
         username: 'admin@internal'
         password: cordoba
         ca_file: /etc/pki/ovirt-engine/ca.pem

     - name: Crea una VM en un cluster de RHV mediante un template.
       ovirt_vms:
         auth: "{{ ovirt_auth }}"
         state: present
         name: ansibleaut
         #template: centos_cloudinit
         template: centos1nic
         cluster: HERDOM
         cpu_cores: 1
         memory: 2GiB
         cloud_init_persist: true
         cloud_init:
           nic_name: eth0
           nic_boot_protocol: static
           nic_ip_address: "{{ num_ip }}" 
           nic_netmask: 255.255.255.0
           nic_gateway: 192.168.105.1
           nic_on_boot: true
           host_name: "{{ nombre_host }}" 

     - name: Revoke the SSO token
       ovirt_auth:
         state: absent
         ovirt_auth: "{{ ovirt_auth }}"
