---
     - name: Login to oVirt
       ovirt_auth:
         url: https://rhevm4.herdom.com/ovirt-engine/api
         username: 'admin@internal'
         password: "{{ clave_rhv }}"
         ca_file: /etc/pki/ovirt-engine/ca.pem

     - name: List vms
       ovirt_vms_facts:
         fetch_nested: true
         nested_attributes:
           - description
         auth: "{{ ovirt_auth }}"

     - name: set vms
       set_fact:
          vm: "{{ item.name }}: {{ item.snapshots |
map(attribute='description') | join(',') }}"
       with_items: "{{ ovirt_vms }}"
       loop_control:
         label: "{{ item.name }}"
       register: all_vms

     - name: make a list
       set_fact: vms="{{ all_vms.results | map(attribute='ansible_facts.vm') | list }}"

     - name: Print vms
       debug:
          var: vms

     - name: Revoke the SSO token
       ovirt_auth:
         state: absent
         ovirt_auth: "{{ ovirt_auth }}"
