---
     - name: Login to oVirt
       ovirt_auth:
         url: https://rhevm4.herdom.com/ovirt-engine/api
         username: 'admin@internal'
         password: "{{ clave_rhv }}"
         ca_file: /etc/pki/ovirt-engine/ca.pem

     - name: Borra una VM en un cluster de RHV
       ovirt_vms:
         auth: "{{ ovirt_auth }}"
         state: absent
         name: "{{ nombre_vm }}"
         cluster: HERDOM

     - name: Revoke the SSO token
       ovirt_auth:
         state: absent
         ovirt_auth: "{{ ovirt_auth }}"
