---
- name: Obtiene la fecha del sistema.
  debug:
   msg: "Creando la carpeta en interfaz: {{ interfaz }} con fecha: {{ fecha }} en el servidor {{ node_selector }}"
- name: Crea la carpeta de backup con la fecha.
  win_file:
    path: C:\HERNAN\INTERFACES_PROGS\{{ interfaz }}\BKP\{{ fecha }}
    state: directory
  delegate_to: "{{ node_selector }}"
