---
- name: Obtiene la fecha del sistema.
  debug:
   msg: "Realizando backup de la interfaz: {{ interfaz }}."

- name: Realiza el back-up
  win_copy:
    src: C:\HERNAN\INTERFACES_PROGS\{{ interfaz }}\winzip26.exe
    dest: C:\HERNAN\INTERFACES_PROGS\{{ interfaz }}\BKP\{{ fecha }}\
    remote_src: yes

- name: Realiza el back-up
  win_copy:
    src: C:\HERNAN\INTERFACES_PROGS\{{ interfaz }}\libreria1.dll
    dest: C:\HERNAN\INTERFACES_PROGS\{{ interfaz }}\BKP\{{ fecha }}\
    remote_src: yes

- name: Realiza el back-up
  win_copy:
    src: C:\HERNAN\INTERFACES_PROGS\{{ interfaz }}\Archivo1.txt
    dest: C:\HERNAN\INTERFACES_PROGS\{{ interfaz }}\BKP\{{ fecha }}\
    remote_src: yes

